#!/bin/sh
set -e
export LC_ALL=C

scripts/flac-config
scripts/flac-build $@
scripts/libass-config
scripts/libass-build $@
scripts/ffmpeg-config
scripts/ffmpeg-build $@
scripts/mpv-config
scripts/mpv-build $@
